version: '3.9'

services: 
  admin-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_pass
      POSTGRES_DB: admin_db
    volumes:
      - admin-db-data:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    networks:
      - digital-gate-pass-network

  auth-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - digital-gate-pass-network


  leave-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: leave_user
      POSTGRES_PASSWORD: leave_pass
      POSTGRES_DB: leave_db
    volumes:
      - leave-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - digital-gate-pass-network


  gatepass-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: gatepass_user
      POSTGRES_PASSWORD: gatepass_pass
      POSTGRES_DB: gatepass_db
    volumes:
      - gatepass-db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - digital-gate-pass-network

  notification-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: notification_pass
      POSTGRES_DB: notification_db
    volumes:
      - notification-db-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"  
    networks:
      - digital-gate-pass-network

  redis:
    image: redis:7
    restart: always
    volumes: 
      - redis-data:/data
    ports:
      - "6379:6379" 
    networks:
      - digital-gate-pass-network  

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - digital-gate-pass-network


networks:
  digital-gate-pass-network:
    driver: bridge



volumes:
  auth-db-data:
  leave-db-data:
  pgadmin-data:
  gatepass-db-data:
  notification-db-data:
  admin-db-data:
  redis-data:
